//
//  Task+CoreDataClass.swift
//  ToDo
//
//  Created by Ivan on 02.11.2025.
//

import Foundation
import CoreData

@objc(Task)
public class Task: NSManagedObject {
    // This convenience method is normally auto-generated by Xcode.
    // It allows us to create a fetch request without specifying the entity name as a string.
    @nonobjc public class func fetchRequest() -> NSFetchRequest<Task> {
        return NSFetchRequest<Task>(entityName: "Task")
    }

    // These properties are dynamically managed by the Core Data runtime.
    // The @NSManaged attribute tells the Swift compiler that the storage and implementation
    // for these properties will be provided at runtime.
    @NSManaged public var id: UUID
    @NSManaged public var title: String
    @NSManaged public var taskDescription: String?
    @NSManaged public var status: String
    @NSManaged public var createdAt: Date
}
